version: "3.9"

services:

  db:
    image: postgres:16-alpine
    container_name: stockwex-db

    restart: unless-stopped

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "5434:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data

    networks:
      - stockwex-network

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"


volumes:
  pgdata:
    name: stockwex_pgdata


networks:
  stockwex-network:
    name: stockwex-network
    driver: bridge